name: Schedule

on:
  schedule:
    - cron: "0 9 * * 1"
  push:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Tweet
      run: |
        docker run -it --rm \
        -e TWITTER_ACCESS_TOKEN="${{ secrets.TWITTER_ACCESS_TOKEN }}" \
        -e TWITTER_ACCESS_TOKEN_SECRET="${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}"
        -e TWITTER_CONSUMER_KEY="${{ secrets.TWITTER_CONSUMER_KEY }}" \
        -e TWITTER_CONSUMER_KEY_SECRET="${{ secrets.TWITTER_CONSUMER_KEY_SECRET }}" \
        -e WAKATIME_API_KEY="${{ secrets.WAKATIME_API_KEY }}" \
        ghcr.io/inkohx/wakatime-tweet-activity:latest
