name: Schedule

on:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://ghcr.io/inkohx/wakatime-tweet-activity:1.0.0
      env:
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_KEY_SECRET: ${{ secrets.TWITTER_CONSUMER_KEY_SECRET }}
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
